os: linux 
arch: arm64 
dist: bionic # Ubuntu 18

language: c

services:
  - docker

# requires that commit is for a PR or is on master branch
if: (type = pull_request) OR (type = push AND branch = master)

install: skip

# DOCKER_USERNAME is defined as a repository secret environment variable on travis-ci.org
before_script:
  - docker pull ${DOCKER_USERNAME}/c-runtime:arm32
  - docker run -d ${DOCKER_USERNAME}/c-runtime:arm32 sleep 5m  # Runs the docker container as detached

script:
  - docker cp . $(docker ps -q):/root/runtime/ # Copy the newest code into the image
  - docker exec -t $(docker ps -q) bash -c "./build.sh" # Build the latest code
  - docker exec -d $(docker ps -q) bash -c "./run.sh"   # Run the Runtime processes
  - docker exec -t $(docker ps -q) bash -c "sleep 5 && cd net_handler && ./tcp_client 1 && ./udp_client"  # Run both test clients
  - docker stop -t 1 $(docker ps -q) # Stop the container when tests finish

deploy:
  provider: script
  skip_cleanup: true
  script: travis_wait bash docker/build_and_push.sh
  on:
    branch: master
    condition: $TRAVIS_EVENT_TYPE = push
