os: linux 
arch: arm64 
dist: bionic # Ubuntu 18

language: c

env:
  - TAG=latest

services:
  - docker

# requires that commit is for a PR or is on master branch
if: (type = pull_request) OR (type = push AND branch = master)

install: skip

before_script:
  - docker build -t ${DOCKER_USERNAME}/c-runtime:$TAG -f docker/Dockerfile . # Build new image with updated code

script:
  - docker run -d ${DOCKER_USERNAME}/c-runtime:$TAG # Runs the docker container as detached
  - docker exec -t $(docker ps -q) bash -c "sleep 5 && cd net_handler && ./tcp_client 1 && ./udp_client"  # Run both test clients
  - docker kill -s INT $(docker ps -q) # Kill the current container
  - docker run -t ${DOCKER_USERNAME}/c-runtime:$TAG ./test.sh # Runs the integration tests in a new container

# DOCKER_USERNAME and DOCKER_ACCESS_TOKEN are defined as a repository secret environment variable on travis-ci.org
before_deploy:
  - echo "$DOCKER_ACCESS_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin

deploy:
  provider: script
  script: docker push ${DOCKER_USERNAME}/c-runtime:$TAG
  on:
    branch: master
  edge: true
