os: linux 
arch: arm64 
dist: bionic # Ubuntu 18

language: c

services:
  - docker

# require the branch name to be master (note for PRs this is the base branch name)
# branches:
#   only:
#     - master

if: (type = push AND branch = master) OR (type = pull_request)

before_install:
  - docker pull ${DOCKER_USERNAME}/c-runtime:arm32

script:
  - docker run -d -p 8101:8101/tcp -p 9000:9000/udp ${DOCKER_USERNAME}/c-runtime:arm32 
  - docker ps
  - sleep 5
  - docker exec -t $(docker ps -n=1 -q) bash -c "cd net_handler && ./tcp_client 1; ./udp_client"
  - docker kill -s INT $(docker ps -n=1 -q)
