os: linux 
arch: arm64 
dist: bionic # Ubuntu 18

language: c

services:
  - docker

# requires that commit is for a PR or is on master branch
if: (type = pull_request) OR (type = push AND branch = master)

env:
  - DOCKER_CLI_EXPERIMENTAL=enabled

install: skip

# DOCKER_USERNAME is defined as a repository secret environment variable on travis-ci.org
before_script:
  - docker pull ${DOCKER_USERNAME}/c-runtime:arm32
  - docker run -d ${DOCKER_USERNAME}/c-runtime:arm32 sleep 5m  # Runs the docker container as detached

script:
  - docker cp . $(docker ps -q):/root/runtime/ # Copy the newest code into the image
  - docker exec -t $(docker ps -q) bash -c "./build.sh" # Build the latest code
  - docker exec -d $(docker ps -q) bash -c "./run.sh"   # Run the Runtime processes
  - docker exec -t $(docker ps -q) bash -c "sleep 5 && cd net_handler && ./tcp_client 1 && ./udp_client"  # Run both test clients
  - docker stop -t 1 $(docker ps -q) # Stop the container when tests finish

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # - docker buildx create --use
  # - travis_wait docker buildx build --push --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from avsurfer123/c-runtime:arm32 -t avsurfer123/c-runtime:arm32 -f docker/Dockerfile .
  - docker pull arm32v7/debian:buster
  - DOCKER_BUILDKIT=1 travis_wait docker build --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from avsurfer123/c-runtime:arm32 -t avsurfer123/c-runtime:arm32 -f docker/Dockerfile .

deploy:
  provider: script
  script: docker push ${DOCKER_USERNAME}/c-runtime:arm32
  on:
    branch: master
  edge: true
