os: linux 
arch: arm64 
dist: bionic # Ubuntu 18

language: c

services:
  - docker

# require the branch name to be master (note for PRs this is the base branch name)
branches:
  only:
    - master


before_install:
  - docker pull ${DOCKER_USERNAME}/c-runtime:arm32

script:
  - docker run -i --rm -p 8101:8101/tcp -p 9000:9000/tcp ${DOCKER_USERNAME}/c-runtime:arm32 cd shm_wrapper && ./static_dev &
  - ls

