version: '3.8'

services:
    runtime:
        build:
            context: .
            dockerfile: docker/Dockerfile
        image: pierobotics/c-runtime:latest
        volumes:
            # Changes in local c-runtime/ and container /root/runtime are synced
            - .:/root/runtime
