version: '3.8'

services:
    runtime:
        build:
            context: .
            dockerfile: docker/Dockerfile
        image: pierobotics/runtime:latest
        command: bash -c "./runtime build && tail -f /dev/null"
        volumes:
            # Changes in local runtime/ and container /root/runtime are synced
            - .:/root/runtime
        ports:
            - "5005:5005" # Used to connect SoundDevice to localhost
