version: '3.8'

services:
    runtime:
        build:
            context: .
            dockerfile: docker/Dockerfile
        image: pierobotics/runtime:latest
        command: bash -c "./runtime build && ./runtime run"
        volumes:
            # Changes in local runtime/ and container /root/runtime are synced
            - .:/root/runtime
