version: '3'
services:
    runtime:
        image: avsurfer123/c-runtime:latest
        volumes:
            # Changes in local /c-runtime and container /root/runtime are synced
            - .:/root/runtime
